# Site settings
title: I_I
SEOTitle: 小肥柴MoMoQQ  
header-img: img/post-bg-desk.jpg
email: qjl625@sina.com
description: "No No No."
keyword: "BY, BY Blog, MoMoQQ, 小肥柴"
url: "http://mmqq.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'

# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     MoMoQQ
#zhihu_username:     MoMoQQ
github_username:    mmqq
#facebook_username:  
jianshu_username:   59a10756e01b
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 4
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: mmqq12




# Gitalk
gitalk:
  enable: true   #是否开启Gitalk评论
  clientID: 5d1012cac01aac2b4acf                            #生成的clientID
  clientSecret: 665dd514b90665365fc9ea694efb4d5b9a3f11ed    #生成的clientSecret
  repo: mmqq.github.io    #仓库名称
  owner: mmqq   #github用户名
  admin: mmqq
  distractionFreeMode: true #是否启用类似FB的阴影遮罩





# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: dcf7517b3603e745937720155b8a8c32

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/59a10756e01b"
    }
]
 
